name: ck-builder
run-name: cm-${{ inputs.variant }}-${{ inputs.platform }}

on:
  workflow_dispatch:
    inputs:
      variant:
        type: choice
        description: Please select a build variant
        default: brew
        required: true
        options:
          - macos-base-native
          - macos-base-universal
          - macos-adv-brew
          - macos-adv-full
          - macos-adv-nomp3
          - macos-adv-light
          - linux-base-alsa
          - linux-base-pulse
          - linux-base-jack
          - linux-base-all
          - linux-adv-alsa
          - linux-adv-pulse
          - linux-adv-jack
          - linux-adv-all
      platform:
        type: choice
        description: Please select a supported platform
        default: macos-latest
        required: true
        options: 
          - macos-14
          - macos-13
          - macos-12
          - ubuntu-24.04
          - ubuntu-22.04
          - ubuntu-20.04

# env:
#   arch: darwin-x86

jobs:
  build:
    runs-on: ${{ inputs.platform }}

    steps:

    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'
        fetch-depth: '0'

    - uses: benjlevesque/short-sha@v3.0
      id: short-sha
      with:
        length: 7

    - name: Cache downloads
      id: cache-downloads
      uses: actions/cache@v4
      env:
        cache-name: ck-cache-1
      with:
        path: build/thirdparty/downloads
        key: $${{ env.cache-name }}-${{ hashFiles('source/scripts/dep/install_libfaust.sh') }}

    - name: install macOS dependencies
      if: startsWith(inputs.platform, 'macos')
      run: brew install bison flex autogen automake flac libogg libvorbis opus mpg123 lame \
                rubberband libsamplerate

    - name: install Linux dependencies
      if: startsWith(inputs.platform, 'ubuntu')
      run: sudo apt update && sudo apt upgrade && sudo apt install bison flex libsndfile1-dev \
                libasound2-dev libpulse-dev libjack-jackd2-dev libmp3lame-dev libresample1-dev \
                librubberband-dev

    - name: build external
      run: make ${{ inputs.variant }}

    - name: create package for distribution
      run: make package

    - uses: actions/upload-artifact@v4
      with:
        name: ${{ github.event.repository.name }}-${{ inputs.variant }}-${{ runner.os }}-${{ runner.arch }}-${{ env.SHA }}
        path: build/dist/${{ github.event.repository.name }}

