name: ck-builder
run-name: cm-${{ inputs.variant }}-${{ inputs.platform }}

on:
  workflow_dispatch:
    inputs:
      variant:
        type: choice
        description: Please select a build variant
        default: macos-adv-brew
        required: true
        options:
          - macos-base-native
          - macos-base-universal
          - macos-adv-brew
          - macos-adv-full
          - macos-adv-nomp3
          - macos-adv-light
      platform:
        type: choice
        description: Please select a supported platform
        default: macos-14
        required: true
        options: 
          - macos-14
          - macos-13
          - macos-12


jobs:
  build:
    runs-on: ${{ inputs.platform }}

    steps:

    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'
        fetch-depth: '0'

    - uses: benjlevesque/short-sha@v3.0
      id: short-sha
      with:
        length: 7

    - name: Cache downloads
      id: cache-downloads
      uses: actions/cache@v4
      env:
        cache-name: ck-cache-1
      with:
        path: build/thirdparty/downloads
        key: $${{ env.cache-name }}-${{ hashFiles('source/scripts/dep/install_libfaust.sh') }}

    - name: install dependencies
      run: brew install bison flex autogen automake flac libogg libvorbis opus mpg123 lame rubberband libsamplerate

    - name: build external
      run: make ${{ inputs.variant }}

    - name: create package for distribution
      run: make package

    - uses: actions/upload-artifact@v4
      with:
        name: ${{ github.event.repository.name }}-${{ inputs.variant }}-${{ runner.os }}-${{ runner.arch }}-${{ env.SHA }}
        path: build/dist/${{ github.event.repository.name }}

